FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

COPY . .

EXPOSE 8281

CMD ["sh", "-c", "until nc -z postgres_db 5432; do sleep 1; done && npx prisma db push && node src/app.js"]